spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/privmall
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration: # Resource Server 에 대한 Client 로 자신을 등록하고 싶다는 의미.

          google:     # /oauth2/authorization/google 주소를 동작하게 한다 == Authorization Endpoint (Authorization Server)
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          github:     # /oauth2/authorization/github 주소를 동작하게 한다 == Authorization Endpoint (Authorization Server)
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          facebook:   # /oauth2/authorization/facebook 주소를 동작하게 한다 == Authorization Endpoint (Authorization Server)
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - public_profile
              - email

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver   # Spring 에서 기본적으로 지원하는 Provider 인 GITHUB, GOOGLE, FACEBOOK 에서는 http://localhost:8080/login/oauth2/code 까지가 스프링에서 사용하는 고정 redirect_uri 값임. --> 현재등록하는 Provider 인 naver 는 Spring 에서 지원하는 Provider 가 아니기 때문에, 아무거나 명시해주어도 되지만, 스프링에서 디폴트로 사용중인 redirect_uri(Callback URI) 를 따르는 것임.

        provider: # naver 는 Spring 이 지원하는 Provider 가 아니기 때문에, provider 를 등록해주어야 함.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    sql: debug
#  web:
#    resources:
#      static-locations: file://D:/SpringProject/uploaddir

